### PR TITLE
Add Red Hat logo as a fonticon

### PR DESCRIPTION
**Pull request by PanSpagetka**
I tried to add new RedHat logo as a fonticon. I would like to use it in https://github.com/RedHatCloudForms/cfme-cloud_services/pull/13

This icon will not be used in ManageIQ, but I don't know a better place to put it. If you have better idea, I am open to suggestions ;)

ping @skateman

### CODE REVIEW

**Comment by skateman** [comment]
As far as I remember we already have it, but @epwinchell will know it better.

**Comment by PanSpagetka** [comment]
I couldn't find it, but maybe i have searched on wrong places

**Comment by epwinchell** [comment]
We don't have one. I'll dig around for a new monochrome version

**Comment by skateman** [comment]
@PanSpagetka also you should not commit the build

**Comment by epwinchell** [comment]
@miq-bot add-reviewer @epwinchell

**Comment by epwinchell** [comment]
@PanSpagetka It appears that using the logo as a monochrome font icon would violate branding policy:
Screen Shot 2019-07-08 at 11 13 13 AM

**Comment by epwinchell** [comment]
@PanSpagetka Branding policy requires that the standalone logo be red. I sent you a black version to use that we can then colored in the stylesheet with a value of #ee0000 @skateman can help with that, I think.

**Comment by epwinchell** [comment]
@PanSpagetka Just remember, you must color it using #ee0000 in the product.

**Pull request merged**
